ariston_set_data:
  fields:
    entity_id:
      required: true
      example: water_heater.aqua_ariston
      selector:
        device:
          integration: "aquaariston"
          entity:
            domain: water_heater
    mode:
      example: manual
      selector:
        select:
          translation_key: "mode"
          options:
            - "manual"
            - "program"
            - "night"
            - "i-memory"
            - "boost"
            - "green"
    required_temperature:
      example: 45
    required_showers:
      example: 2
    antilegionella_set_temperature:
      example: 70
    power:
      example: true
    eco:
      example: true
